const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const html=fs.readFileSync('alumni-map.html','utf8'),code=[...html.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/g)].at(-1)[1];
function harness(result){const elements=new Map(),queries=[];function el(id){if(!elements.has(id))elements.set(id,{dataset:{},value:'',textContent:'',innerHTML:'',hidden:false,disabled:false,classList:{remove(){},toggle(){}},close(){},showModal(){},addEventListener(){},scrollIntoView(){},reportValidity(){return true}});return elements.get(id)}const sb={auth:{onAuthStateChange(){},getSession:async()=>({data:{session:null}})},from(table){queries.push(table);const q={select(){return q},eq(){return q},order:async()=>result};return q;}};for(const id of ['regionFilter','categoryFilter','generationFilter','addressFilter']){el(id).value='all';el(id).options=[{textContent:'전체'}];el(id).selectedIndex=0;}const context=vm.createContext({window:{supabase:{createClient:()=>sb}},document:{getElementById:el,querySelectorAll:()=>[]},URL,location:{origin:'https://example.com',pathname:'/alumni-map.html'},console:{error(){}},alert(){},confirm:()=>false});vm.runInContext(code,context);return{context,elements,queries,el};}
test('uses existing published places schema and restores all rows',async()=>{const rows=Array.from({length:30},(_,i)=>({id:i+1,name:'업장 '+i,owner_generation:'2기',region:'서울'}));const h=harness({data:rows,error:null});await new Promise(setImmediate);assert.deepEqual(h.queries,['hanjogo_alumni_places']);assert.equal((h.el('grid').innerHTML.match(/<article /g)||[]).length,30);assert.ok(!h.el('grid').innerHTML.includes('2기기'));h.el('q').value='업장 29';vm.runInContext('draw()',h.context);assert.equal((h.el('grid').innerHTML.match(/<article /g)||[]).length,1);});
test('API error stays visible instead of appearing as an empty list',async()=>{const h=harness({data:null,error:new Error('missing relation')});await new Promise(setImmediate);assert.equal(h.el('retryBtn').hidden,false);assert.match(h.el('loadStatus').textContent,/불러오지 못/);});
test('unsafe links are rejected and owner matching requires confirmed email',()=>{const h=harness({data:[],error:null});assert.equal(vm.runInContext("safeUrl('javascript:alert(1)')",h.context),'');assert.equal(vm.runInContext("safeUrl('https://instagram.com/test')",h.context),'https://instagram.com/test');// 담당 업장 목록은 서버(place_mine)가 알려줍니다. 공개 조회에는 담당자 이메일이 없습니다.
assert.equal(vm.runInContext("myPlaceIds=new Set([7]);session={user:{email:'owner@example.com'}};mine({id:7})",h.context),false,'이메일 인증 전에는 수정 권한이 없어야 합니다');
assert.equal(vm.runInContext("session={user:{email:'owner@example.com',email_confirmed_at:'2026-10-05'}};mine({id:7})",h.context),true);
assert.equal(vm.runInContext("mine({id:8})",h.context),false,'담당하지 않는 업장은 수정할 수 없어야 합니다');});

test('combines region, category, cohort, address and multiword search; reset restores rows',async()=>{const rows=[{id:1,name:'렁팡스',owner_name:'김태민',owner_generation:'2기',region:'서울',category:'레스토랑',is_address_verified:true},{id:2,name:'카페 하나',owner_name:'김하나',owner_generation:'2기',region:'서울',category:'카페·디저트',is_address_verified:false},{id:3,name:'미확인 업장',category:'기타'}];const h=harness({data:rows,error:null});await new Promise(setImmediate);h.el('q').value='김태민 2기';h.el('regionFilter').value='서울';h.el('categoryFilter').value='restaurant';h.el('generationFilter').value='2';h.el('addressFilter').value='verified';assert.equal(vm.runInContext('filtered().length',h.context),1);h.el('addressFilter').value='pending';assert.equal(vm.runInContext('filtered().length',h.context),0);vm.runInContext('resetFilters()',h.context);assert.equal(vm.runInContext('filtered().length',h.context),3);h.el('regionFilter').value='unknown';assert.equal(vm.runInContext('filtered()[0].id',h.context),3);});
test('mixed categories match each relevant group',()=>{const h=harness({data:[],error:null});assert.equal(vm.runInContext("categoryMatches({category:'카페·디저트'},'cafe') && categoryMatches({category:'카페·디저트'},'bakery')",h.context),true);});
